---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - shell: buildah --version
    register: buildah_test_output
  - name: buildah --version
    debug:
      msg: '{{ buildah_test_output.stdout }}'
