---
- name: Testing andrewrothstein.buildah
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'buildah --version'
      ansible.builtin.shell: buildah --version
      changed_when: false
      register: buildah_test_output
    - name: Output of 'buildah --version'
      ansible.builtin.debug:
        msg: '{{ buildah_test_output.stdout }}'
