---
- name: Installing...
  when: buildah_pkg_mgr is defined
  ansible.builtin.include_tasks: '{{ buildah_pkg_mgr }}.yml'
- name: Installing buildah
  become: true
  become_user: root
  ansible.builtin.package:
    name: '{{ buildah_os_pkgs | default("buildah") }}'
    state: present
